# Generated by Django 5.1.1 on 2026-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cats', through='tags.CatTag', to='tags.tag'),
        ),
    ]
